### ISSUE TITLE
[S2-LP][Driver][EN] To integrate / develop driver for S2-LP with 6LoWPAN protocol

### ISSUE THREAD

**Issue by ralcaide** [Sinapse-Energia/EC-LC-NEMA#23]
The current EC-NEMA is using Sinapse RF in the Northbound to communicate with Gateways.
In this new version, the communication with the Gateways / Edge Router will be done using 6LowPAN (S2-LP). The FW provided by ST should be integrated / adapted in order to provide 6LoWPAN connectivity to EC-NEMA. The MCU is **STM32F030CC**

Here the FW provided by ST:
1. https://www.st.com/content/st_com/en/products/embedded-software/mcus-embedded-software/stm32-embedded-software/stm32-ode-function-pack-sw/fp-sns-6lpnode1.html

2. https://www.st.com/content/st_com/en/products/embedded-software/mcus-embedded-software/stm32-embedded-software/stm32cube-expansion-packages/x-cube-subg1.html

This work should be done here: https://github.com/Sinapse-Energia/EC-LC-NEMA/tree/6LoWPAN_Droid

**Comment by ralcaide** [comment]
The second FW provided contains a UPD receiver / sender that could be useful for our application

**Comment by vAnArhist** [comment]
Integrating now UDP sender at node.

**Comment by ralcaide** [comment]
Very important question: 
The current HW is usable or should be modified? Is it possible to init the device using other FW configuration or not? 
It would be great if was can use the current HW without modification

**Comment by ralcaide** [comment]
Could you please explain here the modifications you've done in the HW in order to init the device and be able to perform communications?

**Comment by ralcaide** [comment]
@vAnArhist , please provide current status and modifications performed

**Comment by vAnArhist** [comment]
After review the code and checking work of Nema nodes we mentioned that radio library wouldn`t work without external GPIO for S2LP. 
<a href="http://piccy.info/view3/12891764/f587469b1fd765d29e7335b2c9f48864/orig/" target="_blank"><img src="http://i.piccy.info/i9/206e95751cf6bb91090d9ecf2e03e687/1547201510/98154/1294313/GPIO_MCU_800.jpg" alt="Piccy.info - Free Image Hosting" border="0" /></a><a href="http://i.piccy.info/a3c/2019-01-11-10-11/i9-12891764/692x617-r" target="_blank"><img src="http://i.piccy.info/a3/2019-01-11-10-11/i9-12891764/692x617-r/i.gif" alt="" border="0" /></a>
<a href="http://piccy.info/view3/12891765/54668cf8e292078b5cd000d4931a7520/1200/" target="_blank"><img src="http://i.piccy.info/i9/bd5490cd2054628dad46c80b786ea2a0/1547201553/77560/1294313/GPIO_S2LP_800.jpg" alt="Piccy.info - Free Image Hosting" border="0" /></a><a href="http://i.piccy.info/a3c/2019-01-11-10-12/i9-12891765/800x520-r" target="_blank"><img src="http://i.piccy.info/a3/2019-01-11-10-12/i9-12891765/800x520-r/i.gif" alt="" border="0" /></a>

We soldered that connections and now nodes working.

**Comment by vAnArhist** [comment]
It can be possible, but we must to modificate driver. Today and tomorrow we are working to add commands and discovery mode. If we will add commands faster than expected - we will modify the driver on this weekend. Else, we will modify it on monday.

**Comment by ralcaide** [comment]
Thanks Ivan, please add the commands and the discovery mode with the current driver, then perform tests and push the code, then modify the driver in order to work with the current hardware. 
Please keep us updated with the advancements

**Comment by fpgamcu** [comment]
Information about IPv6 address forming.
Device ID is contained in the Inc/chip_id.h file.
Example of address forming.
96 bit Device id: 
32 bit DEVICE_ID_REG0 = 01234567 
32 bit DEVICE_ID_REG1 = 89ABCDEF 
32 bit DEVICE_ID_REG2 = 02468ACE
16 bit Node Id = DEVICE_ID_REG2 = 8ACE
64 bit Node Mac:
32 bit low part =  DEVICE_ID_REG1 = 89ABCDEF 
32 bit high part = DEVICE_ID_REG2 + DEVICE_ID_REG0 = 02468ACE + 01234567 = 0369D035
MAC = 03 69 D0 35 89 AB CD EF
IP addresses: 2 for each node
Begins with aaaa or fe80
Ends with MAC ^ 02 = 03 69 D0 35 89 AB CD ED
Resulting IP addresses is:
aaaa::edcd:ab89:35d0:6903
fe80::edcd:ab89:35d0:6903

**Comment by ralcaide** [comment]
I don't understand very well how is the IP created, could you please tell us where should we modify to create different IP and also what operations to do in order to get the IP from DEVICE_ID_REG?

Also, how should we use the command 316; to setup devices in the ER?

**Comment by fpgamcu** [comment]
DEVICE_ID_REG0, DEVICE_ID_REG1 and DEVICE_ID_REG2 in Inc/chip_id.h file should be modified in order to change IP.
how to get IP from device ID is explained in previous comment. simplifying it we have next
low 32 bit MAC part is DEVICE_ID_REG1, high 32 bit MAC part is DEVICE_ID_REG2 + DEVICE_ID_REG0.
IP low part is MAC xor 02, in network order
Example:
If
DEVICE_ID_REG0 = 01234567
DEVICE_ID_REG1 = 89ABCDEF
DEVICE_ID_REG2 = 02468ACE
MAC = 89ABCDEF | ((02468ACE + 01234567) << 32) = 0369D03589ABCDEF
IP = aaaa:: MAC XOR 2 in network order = aaaa::edcd:ab89:35d0:6903

usage of 316; is next
316;aaaa::edcd:ab89:35d0:6903;100;

**Comment by fpgamcu** [comment]
Reverted commits and made them more clearly.
Hardware changes required on board to work: connect +3V3 line with VDD line (see schematic).

**Comment by ralcaide** [comment]
I think the IP you wrote contains a mistake , contains "ed" instead "ef", am I right?
For example:

aaaa::e**d**cd:ab89:35d0:6903 should be aaaa::e**f**cd:ab89:35d0:6903

**Comment by fpgamcu** [comment]
yes, contains ed instead of ef, it is because IP is MAC xor 02, MAC contains EF at the end, and EF xor 02 = ED
