### ISSUE TITLE
[NVM] How is done in the legacy code?

### ISSUE THREAD

**Issue by ralcaide** [Sinapse-Energia/EC-LC-NEMA#3]
Several parameters should be saved in the NVM like the group address and TTL. How is done in the legacy code? 

After understand how is done it is necessary to decide if it is the best way or not

**Comment by ralcaide** [comment]
@francisjjp , please explain us how is done

**Comment by francisjjp** [comment]
These are the basic functions:


 void readFromFLASH(void)
{
	uint8_t index=0;
	uint32_t initialAddress= INITIAL_PAGE_ADDRESS;

	for (index=0;index<NUMBERS_HALFWORD_IN_FLASH;index++)
	{

		flashPARAMETERS[2*index] = *(__IO uint16_t *)initialAddress;
		// Retrieve parameters in RAM
		initialAddress+=2;

	}


}

//// FLASH management functions.

void flashUnlock(void)
{
	while ((FLASH->SR & FLASH_SR_BSY)!=0)
	{
		/// exit with some timeout
	}
	if ((FLASH->CR & FLASH_CR_LOCK)!= 0)
	{
		FLASH->KEYR = FLASH_FKEY1;
		FLASH->KEYR = FLASH_FKEY2;
	}
}

void flashPageErase(void)
{
	FLASH->CR |= FLASH_CR_PER;
	FLASH->AR = INITIAL_PAGE_ADDRESS;
	FLASH->CR |= FLASH_CR_STRT;

	while ((FLASH->SR & FLASH_SR_BSY)!= 0)
	{
		// exit with some timeout
	}
	if ((FLASH->SR & FLASH_SR_EOP)!= 0)
	{
		FLASH->SR |= FLASH_SR_EOP;
	}
	else
	{
		// manage the error cases
	}
	FLASH->CR &= ~FLASH_CR_PER;

}

void flashHalfWord(uint8_t offset, uint16_t dato)
{
	uint32_t address= INITIAL_PAGE_ADDRESS+offset;

	FLASH->CR |= FLASH_CR_PG;
	*(__IO uint16_t*)(address)=dato;

	while ((FLASH->SR & FLASH_SR_BSY)!=0)
	{
		// exit with some timeout
	}

	if ((FLASH->SR & FLASH_SR_EOP)!=0)
	{

		FLASH->SR |= FLASH_SR_EOP;
	}
	else
	{
		// manage the error cases
	}
	FLASH->CR &= ~FLASH_CR_PG;
}


void saveParameterToFlash(uint8_t parameter, uint8_t dato)
{
	uint32_t initialAddress= INITIAL_PAGE_ADDRESS;

	readFromFLASH(); //put all flash parameters in RAM

	flashPARAMETERS[parameter]=dato; // data is written in RAM

	flashUnlock();		 //unlock flash
	flashPageErase(); 	 // erase page

	flashHalfWord(POSITION_PARAMETERS_STATUS, 0x01); // 0x01, this value set that "flash has been saved"
	flashHalfWord(POSITION_dirGrupo, flashPARAMETERS[POSITION_dirGrupo]); // 'dirGrupo' is written in flash
	flashHalfWord(POSITION_byteConfig, flashPARAMETERS[POSITION_byteConfig]); // 'byteConfig' is written in flash
	flashHalfWord(POSITION_TTL, flashPARAMETERS[POSITION_TTL]); // 'TTL' is written in flash;
	flashHalfWord(POSITION_flagAlive, flashPARAMETERS[POSITION_flagAlive]); // 'flagAlive' is written in flash;
	flashHalfWord(POSITION_habACKdif, flashPARAMETERS[POSITION_habACKdif]); // 'habACKdif' is written in flash;
	flashHalfWord(POSITION_version, flashPARAMETERS[POSITION_version]); // 'version' is written in flash;

}

**Comment by ralcaide** [comment]
@m-owais , do you understand what we need for the Non Volatile Memory? You can change the methods to manage the NVM if you think there is a better way. Please provide feedback here.

**Comment by ralcaide** [comment]
@m-owais , I suppose these functions are OK and working good. If there is any problem please feedback here. I set the task as tested passed
