### ISSUE TITLE
[6LoWPAN][0-10] Values in 0-10 are too high

### ISSUE THREAD

**Issue by ralcaide** [Sinapse-Energia/EC-LC-NEMA#34]
The output 0-10 is very high in the EC-LC and EC-NEMA. For example the 3;100; provokes 10,7 in the output and this is very dangerous because we can break the drivers.

It is necessary to adjust this output

**Comment by ralcaide** [comment]
@fpgamcu, I think this is very fast to complete and it is very important for us because it is blocking the production of several hundreds of devices. Could you please do that with high priority

**Comment by ralcaide** [comment]
The most important thing and very urgent is that the device should start at 10V and not at 10,7V. @fpgamcu could you do that asap or tell me where should we modify, please?

**Comment by fpgamcu** [comment]
I am not familiar with those code for dimming, it was developed before I start working with 6LP
I will need about a day to study it and check how we can modify it, and additionally about 4-6 hours to calibrate output.

**Comment by ralcaide** [comment]
Ok, thanks. It is not necessary by the moment. We will try to do that internally

**Comment by sinapseenergia** [comment]
It has been calibrated:

Only , it is needed to put in line 20 in Calib_VI.c following array:

uint8_t bModifiedPWM[CNT_SAMPLES_PWM] = {0x00,	  0x37,	  0X58,	0x72,	0X89,	0xA0,	0xB3,	0xC4,	0xD3,	0xE1,	0xF0};

Note: If firmware does not initialize good PWM or firmware hangs before this initialitation, output for 1-10 will be 11.5V. It is needed in following hardwa revision to include some protection as 10V zener.

**Comment by sinapseenergia** [comment]
For current hardware revision you can put in parallel in 1-10volt output, any zener diode as following in list:

https://www.mouser.es/Semiconductors/Discrete-Semiconductors/Diodes-Rectifiers/Zener-Diodes/_/N-ax1mhZ1yzvvqx?P=1yuq69dZ1z0yecxZ1z0z63x&Keyword=10v+zener&FS=True

Anode must be tied to negative 1-10V signal.
Catode must be tied to positive 1-10V signal.

In next hardware revision, one SMD smaller 10v zener diode will be included.

**Comment by ralcaide** [comment]
Ok, we have tested this table and works great. 
@fpgamcu , please integrate it in the original code. Then, we will close the task.

**Comment by ralcaide** [comment]
@fpgamcu, could you please integrate the new calibration table for 0-10V?
It is needed to put in line 20 in Calib_VI.c following array:

uint8_t bModifiedPWM[CNT_SAMPLES_PWM] = {0x00,	0x37,	0X58,	0x72,	0X89,	0xA0,	0xB3,	0xC4,	0xD3, 0xE1,	0xF0};

**Comment by ralcaide** [comment]
It is only valid for NEMA.

It should be done for EC

**Comment by ralcaide** [comment]
Fixed for EC

**Comment by ralcaide** [comment]
Tested OK in 194004
