### ISSUE TITLE
[SB][Relays & PWM] Actuation over relays and set dimming

### ISSUE THREAD

**Issue by ralcaide** [Sinapse-Energia/EC-LC-NEMA#5]
To implement the the command Set Relays and Dimming explained here: 

[RF Sinapse API](https://github.com/Sinapse-Energia/EC-LC-NEMA/wiki/RF-Sinapse-API)

The EC should be able to:

- Receive the command
- If the command for it, set the required status in the output relay & pwm, for example 1 / 100 or 1 / 50 or 0 / 0
- Send a response, if the received command is asking for it

**Comment by ralcaide** [comment]
Done and pushed a first version. To be tested

**Comment by ralcaide** [comment]
Comment by Muhammad:

> I inverted the PWM generated waveform in code.
Looks like i get 4.7V at 0x00 dimmer value and about 11.9V with 0xFF dimmer value
not sure why not going all way down to 0 V

@francisjjp , is this normal?

Our goal is to create a FW totally compatible with the legacy version. It is to say, the third party clients will send same commands so the legacy version and new version should work same way when receive same command

**Comment by ralcaide** [comment]
It is necessary to calibrate the input to the function in order to get the expected values at the output of the PWM. The calibration should follow the next document

[PWM_calibration_TEST2.xlsx](https://github.com/Sinapse-Energia/EC-LC-NEMA/files/2366069/PWM_calibration_TEST2.xlsx)

**Comment by soporteHW** [comment]
Teste performed here: 
[Test Rail - Set relay & Dimming] (https://sinapseenergia.testrail.io/index.php?/tests/view/1111)

**Comment by ralcaide** [comment]
Verified everything is working as expected
